version: "3.6"

services:
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
        - 27017:27017
    restart: unless-stopped
  app:
    image: remitano-test
    ports:
        - ${PORT}:${PORT}
    environment:
        - DB_HOST=mongo
    restart: unless-stopped
volumes:
 mongodb:
